//! The constant-product curve maths, wei-exact against
//! `../vectors/vectors.json`, with no chain anywhere.
//!
//! That file is generated by arcnow-io/contracts from the very `CurveMath` and
//! `CurveQuote` a live `BondingCurve` settles with, and pinned by
//! sha256 in `../pins.json`. Every row is checked, every field is compared to
//! the wei, and the identities the file states are asserted on every row. A
//! port that is right "almost everywhere" is a port that shows a user a price
//! the chain will not honour.
//!
//! The file is read from the repository root and is not shipped in the crate:
//! it is a proof, not a dependency.

use std::collections::HashMap;

use arcnow_sdk::alloy::primitives::U256;
use arcnow_sdk::curve_math::{self, CurveSnapshot, check_curve_version};
use arcnow_sdk::{CurveParams, Error};
use serde_json::Value;

const VECTORS: &str = include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/../vectors/vectors.json"));

fn file() -> Value {
    serde_json::from_str(VECTORS).expect("vectors.json parses")
}

fn wad(value: &Value) -> U256 {
    value.as_str().unwrap_or_else(|| panic!("{value} is not a decimal string")).parse().unwrap()
}

struct Template {
    params: CurveParams,
    r0: U256,
    y0: U256,
    target: U256,
    curve_supply: U256,
    total_supply: U256,
}

fn templates(file: &Value) -> HashMap<String, Template> {
    file["templates"]
        .as_array()
        .unwrap()
        .iter()
        .map(|t| {
            let r0 = wad(&t["r0Wad"]);
            let y0 = wad(&t["y0Wad"]);
            (
                t["id"].as_str().unwrap().to_owned(),
                Template {
                    params: CurveParams { r0_wad: r0, y0_wad: y0 },
                    r0,
                    y0,
                    target: wad(&t["targetUsdcWad"]),
                    curve_supply: wad(&t["curveSupplyWad"]),
                    total_supply: wad(&t["totalSupplyWad"]),
                },
            )
        })
        .collect()
}

fn fee_bps(file: &Value) -> U256 {
    wad(&file["constants"]["tradeFeeBps"])
}

fn snapshot(t: &Template, reserve: U256, sold: U256, bps: U256) -> CurveSnapshot {
    CurveSnapshot {
        params: t.params,
        reserve_wad: reserve,
        tokens_sold_wad: sold,
        target_quote_wad: t.target,
        curve_supply_wad: t.curve_supply,
        trade_fee_bps: bps,
    }
}

#[test]
fn the_file_is_the_constant_product_curve() {
    let file = file();
    assert_eq!(file["schemaVersion"], 2);
    assert_eq!(file["curve"]["kind"], "constant-product");
    let version = file["curve"]["bondingCurveVersion"].as_str().unwrap();
    check_curve_version(version).expect("the file prices a version this SDK accepts");
}

#[test]
fn every_math_row_matches_to_the_wei() {
    let file = file();
    let rows = file["mathRows"].as_array().unwrap();
    assert_eq!(rows.len(), file["mathRowCount"].as_u64().unwrap() as usize);
    for row in rows {
        let (r0, y0, arg, amount) =
            (wad(&row["r0Wad"]), wad(&row["y0Wad"]), wad(&row["argWad"]), wad(&row["amountWad"]));
        let got = match row["fn"].as_str().unwrap() {
            "usdcReserveAt" => curve_math::usdc_reserve_at(r0, y0, arg),
            "tokenReserveAt" => curve_math::token_reserve_at(r0, y0, arg),
            "spotPriceWad" => curve_math::spot_price_at_reserve_wad(r0, y0, arg),
            "tokensOutForUsdcIn" => curve_math::tokens_out_for_usdc_in(r0, y0, arg, amount),
            "usdcOutForTokensIn" => curve_math::usdc_out_for_tokens_in(r0, y0, arg, amount),
            "usdcInForTokensOut" => curve_math::usdc_in_for_tokens_out(r0, y0, arg, amount),
            "tokensInForUsdcOut" => curve_math::tokens_in_for_usdc_out(r0, y0, arg, amount),
            other => panic!("unknown mathRow fn {other}"),
        }
        .unwrap_or_else(|err| panic!("{row}: {err}"));
        assert_eq!(got, wad(&row["resultWad"]), "{row}");
    }
}

#[test]
fn the_fee_helpers_round_up_exactly_as_the_contracts_do() {
    let file = file();
    let bps = fee_bps(&file);
    for row in file["helpers"]["feeUp"].as_array().unwrap() {
        assert_eq!(
            curve_math::fee_up(wad(&row["amountWad"]), bps).unwrap(),
            wad(&row["feeWad"]),
            "{row}"
        );
    }
    for row in file["helpers"]["grossForNetUp"].as_array().unwrap() {
        assert_eq!(
            curve_math::gross_for_net_up(wad(&row["netWad"]), bps).unwrap(),
            wad(&row["grossWad"]),
            "{row}"
        );
    }
}

#[test]
fn every_template_derives_its_prices_and_its_shape() {
    let file = file();
    let all = templates(&file);
    assert_eq!(all.len(), file["templateCount"].as_u64().unwrap() as usize);
    for t in file["templates"].as_array().unwrap() {
        let id = t["id"].as_str().unwrap();
        let tpl = &all[id];
        assert_eq!(
            curve_math::spot_price_at_reserve_wad(tpl.r0, tpl.y0, tpl.y0).unwrap(),
            wad(&t["initialPriceWad"]),
            "{id} initial price"
        );
        assert_eq!(
            curve_math::spot_price_at_reserve_wad(tpl.r0, tpl.y0, tpl.y0 - tpl.curve_supply)
                .unwrap(),
            wad(&t["graduationPriceWad"]),
            "{id} graduation price"
        );
        assert_eq!(tpl.total_supply - tpl.curve_supply, wad(&t["heldBackWad"]), "{id} held back");

        // The shape: a fee-free buy of each fraction of the target into a fresh
        // curve, and the spot price where it lands.
        let progress = t["shapeProgressBps"].as_array().unwrap();
        let prices = t["shapePriceWad"].as_array().unwrap();
        for (bps, price) in progress.iter().zip(prices) {
            let net = tpl.target * wad(bps) / U256::from(10_000);
            let out = curve_math::tokens_out_for_usdc_in(tpl.r0, tpl.y0, tpl.y0, net)
                .unwrap()
                .min(tpl.curve_supply);
            assert_eq!(
                curve_math::spot_price_at_reserve_wad(tpl.r0, tpl.y0, tpl.y0 - out).unwrap(),
                wad(price),
                "{id} shape at {bps} bps"
            );
        }
    }
}

#[test]
fn every_state_is_reached_by_replaying_its_history() {
    let file = file();
    let all = templates(&file);
    let bps = fee_bps(&file);
    let states = file["states"].as_array().unwrap();
    assert_eq!(states.len(), file["stateCount"].as_u64().unwrap() as usize);
    for state in states {
        let tpl = &all[state["templateId"].as_str().unwrap()];
        let mut s = snapshot(tpl, tpl.r0, U256::ZERO, bps);
        for step in state["history"].as_array().unwrap() {
            let amount = wad(&step["amountWad"]);
            match step["side"].as_str().unwrap() {
                "buy" => {
                    let q = curve_math::quote_buy(&s, amount).unwrap();
                    s.reserve_wad = q.new_reserve_wad;
                    s.tokens_sold_wad = q.new_tokens_sold_wad;
                }
                "sell" => {
                    let q = curve_math::quote_sell(&s, amount).unwrap();
                    s.reserve_wad = q.new_reserve_wad;
                    s.tokens_sold_wad = q.new_tokens_sold_wad;
                }
                other => panic!("unknown side {other}"),
            }
        }
        let id = format!("{}/{}", state["templateId"], state["id"]);
        assert_eq!(s.reserve_wad, wad(&state["reserveWad"]), "{id} reserve");
        assert_eq!(s.tokens_sold_wad, wad(&state["tokensSoldWad"]), "{id} tokens sold");
        assert_eq!(s.reserve_wad - tpl.r0, wad(&state["realReserveWad"]), "{id} real reserve");
        let y = tpl.y0 - s.tokens_sold_wad;
        assert_eq!(y, wad(&state["tokenReserveWad"]), "{id} token reserve");
        assert_eq!(
            curve_math::usdc_reserve_at(tpl.r0, tpl.y0, y).unwrap(),
            wad(&state["positionWad"])
        );
        assert_eq!(curve_math::spot_price_wad(&s).unwrap(), wad(&state["spotPriceWad"]), "{id}");
    }
}

#[test]
fn every_priced_trade_matches_to_the_wei_and_obeys_the_identities() {
    let file = file();
    let all = templates(&file);
    let bps = fee_bps(&file);
    let vectors = file["vectors"].as_array().unwrap();
    assert_eq!(vectors.len(), file["vectorCount"].as_u64().unwrap() as usize);
    assert_eq!(vectors.len(), 504);
    for v in vectors {
        let id = v["id"].as_str().unwrap();
        let tpl = &all[v["templateId"].as_str().unwrap()];
        let s = snapshot(tpl, wad(&v["reserveWad"]), wad(&v["tokensSoldWad"]), bps);
        let amount_in = wad(&v["amountInWad"]);
        let (reserve, sold) = (s.reserve_wad, s.tokens_sold_wad);
        let new_sold = wad(&v["newTokensSoldWad"]);
        let new_reserve = wad(&v["newReserveWad"]);
        let fee = wad(&v["feeUsdcWad"]);
        let delta = wad(&v["reserveDeltaWad"]);
        match v["side"].as_str().unwrap() {
            "buy" => {
                let q =
                    curve_math::quote_buy(&s, amount_in).unwrap_or_else(|e| panic!("{id}: {e}"));
                assert_eq!(q.tokens_out_wad, wad(&v["amountOutWad"]), "{id} tokens out");
                assert_eq!(q.fee_quote_wad, fee, "{id} fee");
                assert_eq!(q.quote_spent_wad, wad(&v["usdcSpentWad"]), "{id} spent");
                assert_eq!(q.refund_wad, wad(&v["refundWad"]), "{id} refund");
                assert_eq!(q.new_reserve_wad, new_reserve, "{id} new reserve");
                assert_eq!(q.new_tokens_sold_wad, new_sold, "{id} new sold");
                assert_eq!(q.new_price_wad, wad(&v["newPriceWad"]), "{id} new price");
                assert_eq!(q.graduates, v["graduates"].as_bool().unwrap(), "{id} graduates");
                // identities
                assert_eq!(new_reserve, reserve + delta, "{id}");
                assert_eq!(delta, amount_in - q.refund_wad - fee, "{id}");
                assert_eq!(q.quote_spent_wad, amount_in - q.refund_wad, "{id}");
                assert_eq!(new_sold, sold + q.tokens_out_wad, "{id}");
            }
            "sell" => {
                let q =
                    curve_math::quote_sell(&s, amount_in).unwrap_or_else(|e| panic!("{id}: {e}"));
                assert_eq!(q.quote_out_wad, wad(&v["amountOutWad"]), "{id} quote out");
                assert_eq!(q.fee_quote_wad, fee, "{id} fee");
                assert_eq!(q.gross_quote_wad, delta, "{id} gross");
                assert_eq!(q.new_reserve_wad, new_reserve, "{id} new reserve");
                assert_eq!(q.new_tokens_sold_wad, new_sold, "{id} new sold");
                assert_eq!(q.new_price_wad, wad(&v["newPriceWad"]), "{id} new price");
                assert!(!v["graduates"].as_bool().unwrap(), "{id}: a sell never graduates");
                // identities
                assert_eq!(new_reserve, reserve - delta, "{id}");
                assert_eq!(delta, q.quote_out_wad + fee, "{id}");
                let (y, y_new) = (tpl.y0 - sold, tpl.y0 - new_sold);
                assert_eq!(
                    delta,
                    curve_math::usdc_reserve_at(tpl.r0, tpl.y0, y).unwrap()
                        - curve_math::usdc_reserve_at(tpl.r0, tpl.y0, y_new).unwrap(),
                    "{id}"
                );
                assert_eq!(new_sold, sold - amount_in, "{id}");
            }
            other => panic!("unknown side {other}"),
        }
        let y_new = tpl.y0 - new_sold;
        let c = curve_math::usdc_reserve_at(tpl.r0, tpl.y0, y_new).unwrap();
        assert_eq!(
            wad(&v["newPriceWad"]),
            c * U256::from(10u64).pow(U256::from(18)) / y_new,
            "{id}"
        );
        assert!(new_reserve >= c, "{id}: the stored reserve is never below C(Y')");
    }
}

#[test]
fn every_launch_quote_matches_to_the_wei() {
    let file = file();
    let all = templates(&file);
    let bps = fee_bps(&file);
    let launch_fee = wad(&file["constants"]["launchFeeWad"]);
    let reference = &all["reference"];
    let fresh =
        CurveSnapshot::fresh(reference.params, reference.target, reference.curve_supply, bps);
    for row in file["launchVectors"].as_array().unwrap() {
        let q = curve_math::quote_launch(&fresh, launch_fee, wad(&row["initialBuyWad"])).unwrap();
        assert_eq!(q.total_cost_wad, wad(&row["totalCostWad"]), "{row}");
        assert_eq!(q.tokens_out_wad, wad(&row["tokensOutWad"]), "{row}");
        assert_eq!(q.trade_fee_wad, wad(&row["tradeFeeWad"]), "{row}");
    }
}

#[test]
fn only_a_version_4_bonding_curve_is_priced() {
    for accepted in ["arcnow/bonding-curve@4.0.0", "arcnow/bonding-curve@4.7.11"] {
        check_curve_version(accepted).unwrap_or_else(|err| panic!("{accepted}: {err}"));
    }
    // A bonding curve of a version this SDK does not price — the retired
    // linear @1.x.x among them — is refused by name, never priced.
    for unknown in [
        "arcnow/bonding-curve@1.0.0",
        "arcnow/bonding-curve@1.2.3",
        // The single-quote curve of the version-2 stack.
        "arcnow/bonding-curve@2.0.0",
        "arcnow/bonding-curve@2.7.11",
        // The multi-quote (v3) curve, retired with its developer share: its buy,
        // sell and previewFeeSplit take a fourth address this ABI does not have.
        "arcnow/bonding-curve@3.0.0",
        "arcnow/bonding-curve@3.7.11",
        "arcnow/bonding-curve@5.0.0",
        "arcnow/bonding-curve@0.9.0",
        "arcnow/bonding-curve@4",
        "arcnow/bonding-curve@4.0",
        "arcnow/bonding-curve@4.0.0-rc1",
    ] {
        let err = check_curve_version(unknown).unwrap_err();
        assert!(
            matches!(&err, Error::UnknownCurveVersion { version } if version == unknown),
            "{unknown:?}: {err:?}"
        );
        assert!(err.to_string().contains(&format!("{unknown:?}")), "the refusal names it: {err}");
    }
    // Not a bonding curve at all — a token, another arcnow.io contract, or a
    // string that is no arcnow.io version — is NOT an unknown curve version.
    for (not_a_curve, says) in [
        ("arcnow/arc-token@1.0.0", "token"),
        ("arcnow/curve-factory@2.0.0", "curve-factory"),
        ("arcnow/platform-config@2.0.0", "platform-config"),
        ("arcnow/arc-now-fee-hook@2.0.0", "arc-now-fee-hook"),
        ("bonding-curve@2.0.0", "bonding-curve@2.0.0"),
        ("", "no arcnow.io version"),
    ] {
        let err = check_curve_version(not_a_curve).unwrap_err();
        assert!(
            matches!(&err, Error::AddressIsNotACurve { address: None, version: Some(v) } if v == not_a_curve),
            "{not_a_curve:?}: {err:?}"
        );
        let message = err.to_string();
        assert!(message.contains(says), "the refusal says what it is: {message}");
        assert!(!message.contains("not a version this SDK can price"), "{message}");
    }
    curve_math::check_platform_version("arcnow/platform-config@4.0.0").unwrap();
    curve_math::check_registry_version("arcnow/platform-registry@4.1.0").unwrap();
    for refused in [
        "arcnow/platform-config@3.0.0",
        "arcnow/platform-config@2.0.0",
        "arcnow/platform-config@1.0.0",
        "arcnow/bonding-curve@4.0.0",
    ] {
        assert!(
            matches!(
                curve_math::check_platform_version(refused),
                Err(Error::UnknownCurveVersion { .. })
            ),
            "{refused}"
        );
    }
    for refused in ["arcnow/platform-registry@3.0.0", "arcnow/platform-registry@2.0.0"] {
        assert!(
            matches!(
                curve_math::check_registry_version(refused),
                Err(Error::UnknownCurveVersion { .. })
            ),
            "{refused}"
        );
    }
}

#[test]
fn the_rest_of_the_stack_is_gated_by_major_too() {
    type Check = fn(&str) -> Result<(), Error>;
    let gates: [(Check, &str, &str); 3] = [
        (
            curve_math::check_quote_registry_version,
            "arcnow/quote-registry@1.0.0",
            "arcnow/quote-registry@2.0.0",
        ),
        (curve_math::check_launchpad_version, "arcnow/launchpad@3.0.0", "arcnow/launchpad@2.0.0"),
        (
            curve_math::check_v4_migrator_version,
            "arcnow/uniswap-v4-migrator@2.0.0",
            "arcnow/uniswap-v4-migrator@1.0.0",
        ),
    ];
    for (check, accepted, refused) in gates {
        check(accepted).unwrap_or_else(|err| panic!("{accepted}: {err}"));
        let err = check(refused).unwrap_err();
        assert!(
            matches!(&err, Error::UnknownCurveVersion { version } if version == refused),
            "{refused}: {err:?}"
        );
    }
}

#[test]
fn a_retired_version_is_named_as_the_stack_it_belonged_to() {
    type Check = fn(&str) -> Result<(), Error>;
    // The 3.x build of every component that moved to 4.x is the retired
    // multi-quote (v3) stack, and the refusal says so by name.
    let retired: [(Check, &str); 3] = [
        (curve_math::check_curve_version, "arcnow/bonding-curve@3.0.0"),
        (curve_math::check_platform_version, "arcnow/platform-config@3.2.0"),
        (curve_math::check_registry_version, "arcnow/platform-registry@3.0.0"),
    ];
    for (check, version) in retired {
        let message = check(version).unwrap_err().to_string();
        assert!(message.contains("retired multi-quote (v3) stack"), "{version}: {message}");
        assert!(message.contains("gone from arcnow.io"), "{version}: {message}");
        assert!(message.contains("wiped"), "{version}: {message}");
        assert!(!message.contains("predates quote tokens"), "{version}: {message}");
    }
    // Anything older than that predates quote tokens as well.
    let older: [(Check, &str); 4] = [
        (curve_math::check_curve_version, "arcnow/bonding-curve@2.0.0"),
        (curve_math::check_platform_version, "arcnow/platform-config@2.0.0"),
        (curve_math::check_launchpad_version, "arcnow/launchpad@2.1.0"),
        (curve_math::check_v4_migrator_version, "arcnow/uniswap-v4-migrator@1.0.0"),
    ];
    for (check, version) in older {
        let message = check(version).unwrap_err().to_string();
        assert!(message.contains("predates quote tokens"), "{version}: {message}");
        assert!(!message.contains("retired multi-quote (v3) stack"), "{version}: {message}");
    }
    // A newer build, or some other contract's VERSION(), is not called old.
    let other: [(Check, &str); 2] = [
        (curve_math::check_platform_version, "arcnow/platform-config@5.0.0"),
        (curve_math::check_platform_version, "arcnow/arc-token@1.0.0"),
    ];
    for (check, version) in other {
        let message = check(version).unwrap_err().to_string();
        assert!(!message.contains("predates quote tokens"), "{version}: {message}");
        assert!(!message.contains("retired multi-quote"), "{version}: {message}");
    }
}
